"""add_product_image_thumbnail_key

Revision ID: 2d2c69a9c6bf
Revises: 12c366335dd4
Create Date: 2026-07-30 21:20:03.453467

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2d2c69a9c6bf'
down_revision: str | Sequence[str] | None = '12c366335dd4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('thumbnail_s3_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'thumbnail_s3_key')
    # ### end Alembic commands ###
