"""add image to categories

Revision ID: 2dbab8a167a4
Revises: 336ec8894286
Create Date: 2026-08-15 07:47:20.382457

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2dbab8a167a4'
down_revision: str | Sequence[str] | None = '336ec8894286'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_s3_key', sa.String(), nullable=True))
    op.add_column('categories', sa.Column('image_thumbnail_s3_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'image_thumbnail_s3_key')
    op.drop_column('categories', 'image_s3_key')
    # ### end Alembic commands ###
