"""add label to addresses

Revision ID: ceba4fef01ff
Revises: 278df48e2ff3
Create Date: 2026-08-12 16:39:17.074186

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ceba4fef01ff'
down_revision: str | Sequence[str] | None = '278df48e2ff3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'label')
    # ### end Alembic commands ###
